# Generated by Django 6.0.5 on 2026-05-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunodesistencia',
            name='nome_responsavel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alunodesistencia',
            name='telefone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alunodesistencia',
            name='telefone_responsavel',
            field=models.CharField(max_length=100),
        ),
    ]
