# Generated by Django 6.0.5 on 2026-05-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_unidade_pessoa_unidade'),
        ('dashboard', '0008_delete_desistencia'),
        ('dashboard_second', '0002_alter_alunodesistencia_nome_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_social', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100, null=True)),
                ('telefone_responsavel', models.CharField(max_length=100)),
                ('data_nascimento', models.DateTimeField()),
                ('cep', models.CharField(max_length=9, null=True)),
                ('rua', models.CharField(max_length=255, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=2, null=True)),
                ('aprendizagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.aprendizagem')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.curso')),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.entidade')),
                ('escolaridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.escolaridade')),
                ('profissional_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.pessoa')),
                ('tipo_formacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.tipoformacao')),
                ('turno_estuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.turnoestuda')),
                ('turno_vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.turnovaga')),
            ],
        ),
    ]
