# Generated by Django 6.0.5 on 2026-05-30 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_sexo_aluno_sexo'),
        ('dashboard_second', '0003_alunoconcluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoconcluido',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.sexo'),
        ),
        migrations.AddField(
            model_name='alunodesistencia',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.sexo'),
        ),
    ]
