# Generated by Django 6.0.5 on 2026-05-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_second', '0004_alunoconcluido_sexo_alunodesistencia_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
