# Generated by Django 6.0.5 on 2026-05-31 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_second', '0005_desistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunodesistencia',
            name='desistencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard_second.desistencia'),
        ),
    ]
