# Generated by Django 6.0.5 on 2026-05-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacao', '0005_unidade_pessoa_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFormacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoEstuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nome_responsavel', models.CharField(verbose_name=100)),
                ('telefone_responsavel', models.CharField(verbose_name=100)),
                ('data_nascimento', models.DateTimeField()),
                ('profissional_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.pessoa')),
                ('aprendizagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.aprendizagem')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.curso')),
                ('entidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.entidade')),
                ('escolaridade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.escolaridade')),
                ('tipo_formacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.tipoformacao')),
                ('turno_estuda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.turnoestuda')),
                ('turno_vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.turnovaga')),
            ],
        ),
    ]
