# Generated by Django 6.0.5 on 2026-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(null=True, verbose_name=100),
        ),
    ]
