# Generated by Django 6.0.5 on 2026-05-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_unidade_pessoa_unidade'),
        ('dashboard', '0002_aluno_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cadastrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='alunos_cadastrados', to='autenticacao.pessoa'),
        ),
    ]
