# Generated by Django 6.0.5 on 2026-05-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_aluno_cadastrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
