# Generated by Django 6.0.5 on 2026-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_aluno_bairro_aluno_cep_aluno_cidade_aluno_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
