# Generated by Django 6.0.5 on 2026-05-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_aluno_nome_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
