# Generated by Django 6.0.5 on 2026-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_aluno_nome_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
