# Generated by Django 6.0.5 on 2026-05-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_desistencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Desistencia',
        ),
    ]
