# Generated by Django 6.0.5 on 2026-05-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
